name: Test Docker Setup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build . -t cs470
    - name: Run script in docker
      run: docker run -v $(pwd):/home/root/cs470 cs470 /home/root/cs470/all.sh